export const CHORD_HPCP_FIXTURE_CASES = [
  { chordName: 'A-Dur', wavFile: 'A-Dur/amaj.wav', expected: { isCorrect: true } },
  { chordName: 'C-Dur', wavFile: 'C-Dur/c_chord.wav', expected: { isCorrect: true } },
  { chordName: 'D-Dur', wavFile: 'D-Dur/d_chord.wav', expected: { isCorrect: true } },
  { chordName: 'E-Dur', wavFile: 'E-Dur/emaj.wav', expected: { isCorrect: true } },
  { chordName: 'F-Dur', wavFile: 'F-Dur/fmaj.wav', expected: { isCorrect: true } },
  { chordName: 'G-Dur', wavFile: 'G-Dur/g_chord.wav', expected: { isCorrect: true } },
  { chordName: 'C-Dur (1-Finger)', wavFile: 'C-Dur (1-Finger)/csimp.wav', expected: { isCorrect: true } },
  { chordName: 'G-Dur (1-Finger)', wavFile: 'G-Dur (1-Finger)/gsimp.wav', expected: { isCorrect: true } },
  { chordName: 'A-Moll', wavFile: 'A-Moll/amin.wav', expected: { isCorrect: true } },
  { chordName: 'D-Moll', wavFile: 'D-Moll/dmin.wav', expected: { isCorrect: true } },
  { chordName: 'E-Moll', wavFile: 'E-Moll/emin.wav', expected: { isCorrect: true } },
  { chordName: 'E-Moll', wavFile: 'E-Moll/eminor_chord.wav', expected: { isCorrect: true } },
  { chordName: 'C7', wavFile: 'C7/c7.wav', expected: { isCorrect: true } },
  { chordName: 'D7', wavFile: 'D7/d7.wav', expected: { isCorrect: true } },
  { chordName: 'C-Dur', wavFile: 'C-Dur/synth.wav', expected: { isCorrect: true } },
  { chordName: 'E-Moll', wavFile: 'E-Moll/synth.wav', expected: { isCorrect: true } },
  { chordName: 'G-Dur', wavFile: 'D-Dur/d_chord.wav', expected: { isCorrect: false, bestMatchContains: 'D-Dur' } },
  { chordName: 'C-Dur', wavFile: '0_strum.wav', expected: { isCorrect: false } },
  { chordName: 'C-Dur', wavFile: 'd_chord_wrong.wav', expected: { isCorrect: false } },
];
