export const CHORD_HPCP_FIXTURE_CASES = [
  { chordName: 'A-Dur', wavFile: 'A-Dur/adur_steel.wav', expected: { isCorrect: true } },
  { chordName: 'A-Dur', wavFile: 'A-Dur/amaj.wav', expected: { isCorrect: true } },
  { chordName: 'A-Moll', wavFile: 'A-Moll/amin.wav', expected: { isCorrect: true } },
  { chordName: 'A-Moll', wavFile: 'A-Moll/amoll_steel.wav', expected: { isCorrect: true } },
  { chordName: 'A-Moll (2-Finger)', wavFile: 'A-Moll (2-Finger)/01.wav', expected: { isCorrect: true } },
  { chordName: 'A7', wavFile: 'A7/01.wav', expected: { isCorrect: true } },
  { chordName: 'A7', wavFile: 'A7/a7_steel.wav', expected: { isCorrect: true } },
  { chordName: 'C-Dur', wavFile: 'C-Dur/c_chord.wav', expected: { isCorrect: true } },
  { chordName: 'C-Dur', wavFile: 'C-Dur/cdur_steel.wav', expected: { isCorrect: true } },
  { chordName: 'C-Dur', wavFile: 'C-Dur/cdur_steel2.wav', expected: { isCorrect: true } },
  { chordName: 'C-Dur', wavFile: 'C-Dur/synth.wav', expected: { isCorrect: true } },
  { chordName: 'C-Dur (1-Finger)', wavFile: 'C-Dur (1-Finger)/csimp.wav', expected: { isCorrect: true } },
  { chordName: 'C-Moll', wavFile: 'C-Moll/01.wav', expected: { isCorrect: true } },
  { chordName: 'C7', wavFile: 'C7/c7_steel.wav', expected: { isCorrect: true } },
  { chordName: 'C7', wavFile: 'C7/c7.wav', expected: { isCorrect: true } },
  { chordName: 'D-Dur', wavFile: 'D-Dur/d_chord.wav', expected: { isCorrect: true } },
  { chordName: 'D-Dur', wavFile: 'D-Dur/ddur_steel.wav', expected: { isCorrect: true } },
  { chordName: 'D-Moll', wavFile: 'D-Moll/dmin.wav', expected: { isCorrect: true } },
  { chordName: 'D-Moll', wavFile: 'D-Moll/dmoll_steel.wav', expected: { isCorrect: true } },
  { chordName: 'D7', wavFile: 'D7/d7_steel.wav', expected: { isCorrect: true } },
  { chordName: 'D7', wavFile: 'D7/d7.wav', expected: { isCorrect: true } },
  { chordName: 'E-Dur', wavFile: 'E-Dur/edur_steel.wav', expected: { isCorrect: true } },
  { chordName: 'E-Dur', wavFile: 'E-Dur/edur_steel1.wav', expected: { isCorrect: true } },
  { chordName: 'E-Dur', wavFile: 'E-Dur/edur_steel2.wav', expected: { isCorrect: false } },
  { chordName: 'E-Dur', wavFile: 'E-Dur/emaj.wav', expected: { isCorrect: true } },
  { chordName: 'E-Moll', wavFile: 'E-Moll/emin.wav', expected: { isCorrect: true } },
  { chordName: 'E-Moll', wavFile: 'E-Moll/eminor_chord.wav', expected: { isCorrect: true } },
  { chordName: 'E-Moll', wavFile: 'E-Moll/emoll_steel1.wav', expected: { isCorrect: false } },
  { chordName: 'E-Moll', wavFile: 'E-Moll/emoll_steel2.wav', expected: { isCorrect: true } },
  { chordName: 'E-Moll', wavFile: 'E-Moll/synth.wav', expected: { isCorrect: true } },
  { chordName: 'E7', wavFile: 'E7/01.wav', expected: { isCorrect: true } },
  { chordName: 'E7', wavFile: 'E7/e7_steel.wav', expected: { isCorrect: true } },
  { chordName: 'F-Dur', wavFile: 'F-Dur/fmaj.wav', expected: { isCorrect: true } },
  { chordName: 'F-Moll', wavFile: 'F-Moll/01.wav', expected: { isCorrect: true } },
  { chordName: 'F7', wavFile: 'F7/01.wav', expected: { isCorrect: true } },
  { chordName: 'F7', wavFile: 'F7/02.wav', expected: { isCorrect: true } },
  { chordName: 'F7', wavFile: 'F7/03.wav', expected: { isCorrect: true } },
  { chordName: 'F7', wavFile: 'F7/04.wav', expected: { isCorrect: true } },
  { chordName: 'G-Dur', wavFile: 'G-Dur/g_chord.wav', expected: { isCorrect: true } },
  { chordName: 'G-Dur (1-Finger)', wavFile: 'G-Dur (1-Finger)/gsimp.wav', expected: { isCorrect: true } },
  { chordName: 'G-Moll', wavFile: 'G-Moll/01.wav', expected: { isCorrect: true } },
  { chordName: 'G7', wavFile: 'G7/01.wav', expected: { isCorrect: true } },
  { chordName: 'G7', wavFile: 'G7/02.wav', expected: { isCorrect: true } },
  { chordName: 'G7', wavFile: 'G7/03.wav', expected: { isCorrect: true } },
  { chordName: 'G7', wavFile: 'G7/04.wav', expected: { isCorrect: true } },
  { chordName: 'G7', wavFile: 'G7/g7_steel.wav', expected: { isCorrect: true } },
  { chordName: 'H-Dur', wavFile: 'H-Dur/01.wav', expected: { isCorrect: true } },
  { chordName: 'H-Moll', wavFile: 'H-Moll/01.wav', expected: { isCorrect: true } },
  { chordName: 'H7 (B7)', wavFile: 'H7 (B7)/01.wav', expected: { isCorrect: true } },
  { chordName: 'H7 (B7)', wavFile: 'H7 (B7)/h7_steel.wav', expected: { isCorrect: true } },
  { chordName: 'G-Dur', wavFile: 'D-Dur/d_chord.wav', expected: { isCorrect: false, bestMatchContains: 'D-Dur' } },
  { chordName: 'C-Dur', wavFile: '0_strum.wav', expected: { isCorrect: false } },
  { chordName: 'C-Dur', wavFile: 'd_chord_wrong.wav', expected: { isCorrect: false } },
];
